spring:
  application:
    name: crypto-trading-system

  datasource:
    url: ${DB_URL:jdbc:h2:mem:db}
    username: ${DB_ADMIN:dev}
    password: ${DB_ADMIN_PASSWORD:123123}
    driverClassName: ${DB_DRIVER:org.h2.Driver}

  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}

  h2:
    console:
      enabled: true
      path: /h2
